### ISSUE TITLE
Package versions in requirements 

### ISSUE THREAD

**Issue by Demesaikiran** [KanishkNavale/Custom-Gym-Env.-for-Deep-Reinforcement-Learning#1]
Can you mention the versions of each module used in the requirement.txt file? There are many compatibility issues raised while installing those. Especially 'gym'

**Comment by KanishkNavale** [comment]
Well! I was näive back then. I thought it was not important to version the requirements. I can say that this was created in 2021 soo it is v0.20.0

**Comment by Demesaikiran** [comment]
Okay
